### ISSUE TITLE
Remove strict cakephp 3.0.* requirement

### ISSUE THREAD

**Issue by adayth** [PhantomWatson/CakePHP-AutoLoginComponent#2]
The require in composer.json is very strict and I can't get updated to cakephp 3.1 without removing it.
´´´
"require": {   "cakephp/cakephp": "3.0.*"},
´´´
I actually have installed cakephp 3.0.x version and this requirement is avoiding me to update cakephp package to 3.1 version.

**Comment by adayth** [comment]
Thanks!

**Comment by adayth** [comment]
Please merge development branch into master to get this change propagated to packagist dev-master.

**Comment by PhantomWatson** [comment]
Done. Thanks for reminding me!

**Comment by adayth** [comment]
:+1:
