### ISSUE TITLE
The "Auth" alias has already been loaded with the following config

### ISSUE THREAD

**Issue by deepakv75** [PhantomWatson/CakePHP-AutoLoginComponent#3]
I am getting this issue

**Comment by PhantomWatson** [comment]
Please post your `AppController::initialize()` code to show how you're loading the component.

**Comment by deepakv75** [comment]
$this->loadComponent('AutoLogin.AutoLogin');
$this->loadComponent('Auth', [
           authenticate' => [
                'MultiFieldForm' => [
                    'userModel' => 'Employees',
                    'fields' => [
                        'username' => 'email',
                        'password' => 'password'
                    ],
                    'additionalFields' => ['contact_number'],
                    'scope' => [
                        'Employees.deleted' => 0,
                        'Employees.status' => 1
                    ]
                ]
            ],
            'loginAction' => [
                'prefix' => 'admin',
                'controller' => 'Employees',
                'action' => 'login'
            ],
            'fbloginAction' => [
                'controller' => 'Users',
                'action' => 'fblogin'
            ],
            'loginRedirect' => [
                'prefix' => 'admin',
                'controller' => 'Dashboard',
                'action' => 'index'
            ],
            'flash' => [
                'element' => 'auth',
                'key' => 'admin',
            ],
            
            'ajaxLogin' => 'Auth/ajaxlogin',
            'authError' => __d('cake', 'You are not authorized to access that location.')
        ]);

**Comment by PhantomWatson** [comment]
If you upgrade to the newest version of this package and make sure that you're loading `AutoLogin.AutoLogin` _after_ loading `Auth`, this error should go away.
